apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pnco8n4gl-nodejs
  janus-idp.io/tekton: pnco8n4gl-nodejs
  backstage.io/kubernetes-id: pnco8n4gl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pnco8n4gl-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
