apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pnco8n4gl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pnco8n4gl-nodejs 
  name: pnco8n4gl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pnco8n4gl-nodejs 
